wandb_version: 1

network_nr:
  desc: null
  value: 6
num_s:
  desc: null
  value: 13
num_e:
  desc: null
  value: 130
adj_matrix:
  desc: null
  value: "[[0 0 1 1 1 0 1 1 1 1 1 1 1]\n [0 0 0 0 0 0 1 1 0 1 1 1 1]\n [0 0 0 0 0\
    \ 0 0 1 0 0 1 1 1]\n [0 0 0 0 0 0 0 0 1 0 0 1 0]\n [0 0 0 0 0 0 1 1 1 1 1 1 1]\n\
    \ [0 0 0 0 0 0 0 0 0 1 1 0 1]\n [0 0 0 0 0 0 0 1 0 1 1 1 1]\n [0 0 0 0 0 0 0 0\
    \ 0 0 0 1 1]\n [0 0 0 0 0 0 0 0 0 0 0 1 0]\n [0 0 0 0 0 0 0 0 0 0 0 0 1]\n [0\
    \ 0 0 0 0 0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0 0\
    \ 0 0 0 0]]"
errors:
  desc: null
  value:
  - 0.05
  - 0.08
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708783634.323477
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.6
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
